-- iABS Stream Hub - Supabase SQL (Schema + RLS Policies)
-- Run this in Supabase SQL Editor.
-- Notes:
-- - Uses Auth-based admin access via table: admin_users
-- - RLS enabled on all content tables; only active admins can write.

-- =========================
-- 0) Admin users (RBAC) + Helpers
-- =========================
create extension if not exists "uuid-ossp";

create table if not exists public.admin_users (
  user_id uuid primary key,
  role text not null default 'admin',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- IMPORTANT: functions that reference tables must come after table creation
create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.admin_users au
    where au.user_id = auth.uid()
      and au.is_active = true
  );
$$;

alter table public.admin_users enable row level security;

-- Allow logged-in user to read their own admin row (needed by the app)
drop policy if exists "admin_users_read_self" on public.admin_users;
create policy "admin_users_read_self"
on public.admin_users for select
to authenticated
using (user_id = auth.uid());

-- Admins can manage admin list
drop policy if exists "admin_users_admin_all" on public.admin_users;
create policy "admin_users_admin_all"
on public.admin_users for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Allow authenticated users to insert themselves as admin (for first admin setup)
drop policy if exists "admin_users_insert_self" on public.admin_users;
create policy "admin_users_insert_self"
on public.admin_users for insert
to authenticated
with check (user_id = auth.uid());

-- =========================
-- 2) Public content tables used by the app
-- =========================

-- Announcements (id=1 ticker, id=2 schedule toggle, id=3 faq toggle)
create table if not exists public.announcements (
  id bigint primary key,
  message text,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

-- Sponsors
create table if not exists public.sponsors (
  id bigint generated by default as identity primary key,
  brand_name text not null,
  promo_code text,
  discount_desc text,
  url text,
  created_at timestamptz not null default now()
);

-- Highlight clips
create table if not exists public.highlight_clips (
  id bigint generated by default as identity primary key,
  title text not null,
  video_url text not null,
  platform text not null default 'youtube',
  created_at timestamptz not null default now()
);

-- Schedule (week)
create table if not exists public.schedule (
  id bigint generated by default as identity primary key,
  day_name text not null,
  stream_plan text,
  time text,
  created_at timestamptz not null default now()
);

-- FAQs
create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now()
);

-- SEO settings (single row id=1)
create table if not exists public.seo_settings (
  id bigint primary key,
  title text,
  description text,
  keywords text,
  updated_at timestamptz not null default now()
);

-- Polls
create table if not exists public.polls (
  id bigint generated by default as identity primary key,
  question text not null,
  options jsonb not null default '[]'::jsonb,
  is_active boolean not null default false,
  created_at timestamptz not null default now()
);

-- Site stats (id=1 total visits)
create table if not exists public.site_stats (
  id bigint primary key,
  visits bigint not null default 0,
  updated_at timestamptz not null default now()
);

-- Daily views chart
create table if not exists public.daily_views (
  id bigint generated by default as identity primary key,
  view_date date not null unique,
  views_count bigint not null default 0,
  created_at timestamptz not null default now()
);

-- =========================
-- 3) New "power" tables (5 new admin sections)
-- =========================

-- Audit log (read-only for admins, written by triggers or admins)
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  action text not null,
  table_name text not null,
  record_id text,
  summary text,
  created_at timestamptz not null default now()
);

-- Media library
create table if not exists public.media_assets (
  id bigint generated by default as identity primary key,
  title text not null,
  asset_url text not null,
  asset_type text not null default 'image',
  created_at timestamptz not null default now()
);

-- Studio Submissions (public can submit, admin must approve)
create table if not exists public.studio_submissions (
  id bigint generated by default as identity primary key,
  title text not null,
  media_url text not null,
  media_type text not null check (media_type in ('image','video')),
  source text not null default 'direct' check (source in ('direct','tiktok','x','instagram','youtube_shorts')),
  preview_url text,
  width int,
  height int,
  placement text default 'feed' check (placement in ('feed','featured')),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  approved_at timestamptz,
  rejected_at timestamptz,
  created_at timestamptz not null default now()
);

-- Likes: one like per device per submission, and max 3 likes per device per day
create table if not exists public.studio_likes (
  id bigint generated by default as identity primary key,
  submission_id bigint not null references public.studio_submissions(id) on delete cascade,
  device_id text not null,
  created_at timestamptz not null default now(),
  unique (submission_id, device_id)
);

create index if not exists studio_likes_device_created_idx on public.studio_likes(device_id, created_at desc);
create index if not exists studio_submissions_status_created_idx on public.studio_submissions(status, created_at desc);

-- Helper: enforce 3 likes/day per device (used in RLS)
create or replace function public.studio_device_likes_today(p_device_id text)
returns int
language sql
stable
as $$
  select count(*)::int
  from public.studio_likes
  where device_id = p_device_id
    and created_at >= (now() - interval '24 hours');
$$;

create or replace function public.studio_is_approved(p_submission_id bigint)
returns boolean
language sql
stable
as $$
  select exists(
    select 1
    from public.studio_submissions s
    where s.id = p_submission_id
      and s.status = 'approved'
  );
$$;

-- Branding settings
create table if not exists public.branding_settings (
  id bigint primary key,
  profile_image_url text,
  background_pc_url text,
  background_mobile_url text,
  updated_at timestamptz not null default now()
);

-- Integrations settings
create table if not exists public.integration_settings (
  id bigint primary key,
  discord_webhook_url text,
  telegram_bot_token text,
  telegram_chat_id text,
  updated_at timestamptz not null default now()
);

-- =========================
-- 4) RLS for public reads + admin writes
-- =========================
do $$
declare
  t text;
begin
  foreach t in array array[
    'announcements','sponsors','highlight_clips','schedule','faqs','seo_settings','polls','site_stats','daily_views',
    'audit_logs','media_assets','studio_submissions','studio_likes','branding_settings','integration_settings'
  ]
  loop
    execute format('alter table public.%I enable row level security;', t);
  end loop;
end $$;

-- Public can read site content
drop policy if exists "public_read_announcements" on public.announcements;
create policy "public_read_announcements" on public.announcements for select to anon, authenticated using (true);

drop policy if exists "public_read_sponsors" on public.sponsors;
create policy "public_read_sponsors" on public.sponsors for select to anon, authenticated using (true);

drop policy if exists "public_read_highlight_clips" on public.highlight_clips;
create policy "public_read_highlight_clips" on public.highlight_clips for select to anon, authenticated using (true);

drop policy if exists "public_read_schedule" on public.schedule;
create policy "public_read_schedule" on public.schedule for select to anon, authenticated using (true);

drop policy if exists "public_read_faqs" on public.faqs;
create policy "public_read_faqs" on public.faqs for select to anon, authenticated using (true);

drop policy if exists "public_read_seo_settings" on public.seo_settings;
create policy "public_read_seo_settings" on public.seo_settings for select to anon, authenticated using (true);

drop policy if exists "public_read_polls" on public.polls;
create policy "public_read_polls" on public.polls for select to anon, authenticated using (true);

drop policy if exists "public_read_site_stats" on public.site_stats;
create policy "public_read_site_stats" on public.site_stats for select to anon, authenticated using (true);

drop policy if exists "public_read_daily_views" on public.daily_views;
create policy "public_read_daily_views" on public.daily_views for select to anon, authenticated using (true);

drop policy if exists "public_read_branding_settings" on public.branding_settings;
create policy "public_read_branding_settings" on public.branding_settings for select to anon, authenticated using (true);

drop policy if exists "public_read_media_assets" on public.media_assets;
create policy "public_read_media_assets" on public.media_assets for select to anon, authenticated using (true);

-- Studio: public read approved, public submit pending
drop policy if exists "public_read_studio_submissions" on public.studio_submissions;
create policy "public_read_studio_submissions"
on public.studio_submissions for select
to anon, authenticated
using (status = 'approved');

drop policy if exists "public_insert_studio_submissions" on public.studio_submissions;
create policy "public_insert_studio_submissions"
on public.studio_submissions for insert
to anon, authenticated
with check (
  status = 'pending'
  and placement = 'feed'
  and media_type in ('image','video')
  and source in ('direct','tiktok','x','instagram','youtube_shorts')
);

-- Studio likes: public can like approved only, and max 3/day per device
drop policy if exists "public_insert_studio_likes" on public.studio_likes;
create policy "public_insert_studio_likes"
on public.studio_likes for insert
to anon, authenticated
with check (
  public.studio_is_approved(submission_id)
  and length(device_id) between 8 and 100
  and public.studio_device_likes_today(device_id) < 3
);

drop policy if exists "public_read_studio_likes" on public.studio_likes;
create policy "public_read_studio_likes"
on public.studio_likes for select
to anon, authenticated
using (public.studio_is_approved(submission_id));

-- Admin-only access (write + sensitive reads)
create or replace function public.admin_only()
returns boolean
language sql
stable
as $$ select public.is_admin(); $$;

-- Generic admin all policy helper (repeat per table)
-- announcements
drop policy if exists "admin_all_announcements" on public.announcements;
create policy "admin_all_announcements" on public.announcements for all to authenticated using (public.admin_only()) with check (public.admin_only());

drop policy if exists "admin_all_sponsors" on public.sponsors;
create policy "admin_all_sponsors" on public.sponsors for all to authenticated using (public.admin_only()) with check (public.admin_only());

drop policy if exists "admin_all_highlight_clips" on public.highlight_clips;
create policy "admin_all_highlight_clips" on public.highlight_clips for all to authenticated using (public.admin_only()) with check (public.admin_only());

drop policy if exists "admin_all_schedule" on public.schedule;
create policy "admin_all_schedule" on public.schedule for all to authenticated using (public.admin_only()) with check (public.admin_only());

drop policy if exists "admin_all_faqs" on public.faqs;
create policy "admin_all_faqs" on public.faqs for all to authenticated using (public.admin_only()) with check (public.admin_only());

drop policy if exists "admin_all_seo_settings" on public.seo_settings;
create policy "admin_all_seo_settings" on public.seo_settings for all to authenticated using (public.admin_only()) with check (public.admin_only());

drop policy if exists "admin_all_polls" on public.polls;
create policy "admin_all_polls" on public.polls for all to authenticated using (public.admin_only()) with check (public.admin_only());

drop policy if exists "admin_all_site_stats" on public.site_stats;
create policy "admin_all_site_stats" on public.site_stats for all to authenticated using (public.admin_only()) with check (public.admin_only());

drop policy if exists "admin_all_daily_views" on public.daily_views;
create policy "admin_all_daily_views" on public.daily_views for all to authenticated using (public.admin_only()) with check (public.admin_only());

drop policy if exists "admin_all_audit_logs" on public.audit_logs;
create policy "admin_all_audit_logs" on public.audit_logs for all to authenticated using (public.admin_only()) with check (public.admin_only());

drop policy if exists "admin_all_media_assets" on public.media_assets;
create policy "admin_all_media_assets" on public.media_assets for all to authenticated using (public.admin_only()) with check (public.admin_only());

-- Admin can manage studio content
drop policy if exists "admin_all_studio_submissions" on public.studio_submissions;
create policy "admin_all_studio_submissions" on public.studio_submissions
for all to authenticated using (public.admin_only()) with check (public.admin_only());

drop policy if exists "admin_all_studio_likes" on public.studio_likes;
create policy "admin_all_studio_likes" on public.studio_likes
for all to authenticated using (public.admin_only()) with check (public.admin_only());

drop policy if exists "admin_all_branding_settings" on public.branding_settings;
create policy "admin_all_branding_settings" on public.branding_settings for all to authenticated using (public.admin_only()) with check (public.admin_only());

drop policy if exists "admin_all_integration_settings" on public.integration_settings;
create policy "admin_all_integration_settings" on public.integration_settings for all to authenticated using (public.admin_only()) with check (public.admin_only());

-- =========================
-- 5) Audit triggers (optional but powerful)
-- =========================
create or replace function public.audit_trigger_fn()
returns trigger
language plpgsql
security definer
as $$
declare
  rid text;
begin
  rid := coalesce((to_jsonb(coalesce(new, old))->>'id'), null);
  insert into public.audit_logs(actor_user_id, action, table_name, record_id, summary)
  values (
    auth.uid(),
    tg_op,
    tg_table_name,
    rid,
    case
      when tg_op = 'INSERT' then 'Created record'
      when tg_op = 'UPDATE' then 'Updated record'
      when tg_op = 'DELETE' then 'Deleted record'
      else 'Action'
    end
  );
  return coalesce(new, old);
end;
$$;

-- Attach triggers to key tables
do $$
begin
  -- Clean old triggers if exist
  execute 'drop trigger if exists audit_announcements on public.announcements;';
  execute 'drop trigger if exists audit_sponsors on public.sponsors;';
  execute 'drop trigger if exists audit_highlight_clips on public.highlight_clips;';
  execute 'drop trigger if exists audit_schedule on public.schedule;';
  execute 'drop trigger if exists audit_faqs on public.faqs;';
  execute 'drop trigger if exists audit_seo_settings on public.seo_settings;';
  execute 'drop trigger if exists audit_polls on public.polls;';
  execute 'drop trigger if exists audit_media_assets on public.media_assets;';
  execute 'drop trigger if exists audit_studio_submissions on public.studio_submissions;';
  execute 'drop trigger if exists audit_studio_likes on public.studio_likes;';
  execute 'drop trigger if exists audit_branding_settings on public.branding_settings;';
  execute 'drop trigger if exists audit_integration_settings on public.integration_settings;';

  execute 'create trigger audit_announcements after insert or update or delete on public.announcements for each row execute function public.audit_trigger_fn();';
  execute 'create trigger audit_sponsors after insert or update or delete on public.sponsors for each row execute function public.audit_trigger_fn();';
  execute 'create trigger audit_highlight_clips after insert or update or delete on public.highlight_clips for each row execute function public.audit_trigger_fn();';
  execute 'create trigger audit_schedule after insert or update or delete on public.schedule for each row execute function public.audit_trigger_fn();';
  execute 'create trigger audit_faqs after insert or update or delete on public.faqs for each row execute function public.audit_trigger_fn();';
  execute 'create trigger audit_seo_settings after insert or update or delete on public.seo_settings for each row execute function public.audit_trigger_fn();';
  execute 'create trigger audit_polls after insert or update or delete on public.polls for each row execute function public.audit_trigger_fn();';
  execute 'create trigger audit_media_assets after insert or update or delete on public.media_assets for each row execute function public.audit_trigger_fn();';
  execute 'create trigger audit_studio_submissions after insert or update or delete on public.studio_submissions for each row execute function public.audit_trigger_fn();';
  execute 'create trigger audit_studio_likes after insert or update or delete on public.studio_likes for each row execute function public.audit_trigger_fn();';
  execute 'create trigger audit_branding_settings after insert or update or delete on public.branding_settings for each row execute function public.audit_trigger_fn();';
  execute 'create trigger audit_integration_settings after insert or update or delete on public.integration_settings for each row execute function public.audit_trigger_fn();';
end $$;

-- =========================
-- 6) Seed minimal required rows
-- =========================
insert into public.site_stats(id, visits)
values (1, 0)
on conflict (id) do nothing;

insert into public.seo_settings(id, title, description, keywords)
values (1, 'iABS STREAM HUB', 'تابع بثوث iABS المباشرة', 'iABS, Kick, بث مباشر, ألعاب')
on conflict (id) do nothing;

insert into public.branding_settings(id, profile_image_url, background_pc_url, background_mobile_url)
values (1, null, null, null)
on conflict (id) do nothing;

insert into public.integration_settings(id, discord_webhook_url, telegram_bot_token, telegram_chat_id)
values (1, null, null, null)
on conflict (id) do nothing;

-- For announcements toggles:
insert into public.announcements(id, message, is_active)
values
  (1, '', false),
  (2, 'schedule_toggle', true),
  (3, 'faq_toggle', true)
on conflict (id) do nothing;

-- Optional: seed schedule days if empty
insert into public.schedule(day_name, stream_plan, time)
select x.day_name, '', ''
from (values
  ('Saturday'),('Sunday'),('Monday'),('Tuesday'),('Wednesday'),('Thursday'),('Friday')
) as x(day_name)
where not exists (select 1 from public.schedule);

